# Generated by Django 3.2 on 2021-05-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
