# Generated by Django 3.2 on 2021-05-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_published_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='published_timestamp',
            new_name='publish_timestamp',
        ),
    ]
